cat("[SOURCES][INFO] Loading required libraries\n")
library("devtools")
source("pkgChecker.R", chdir = TRUE)

cat("[SOURCES][INFO] Loading required sources\n")
source("source/data/Dataset.R", chdir=TRUE)
source("source/data/Subset.R", chdir=TRUE)
source("source/data/TrainSet.R", chdir=TRUE)

cat("[SOURCES][INFO] Loading clustering algorithms\n")
#LOAD CLUSTERING ALGORITHMS CLASSES

source("source/clustering/heuristics/GenericHeuristic.R", chdir = TRUE)
source("source/clustering/heuristics/ChiSquareHeuristic.R", chdir = TRUE)
source("source/clustering/heuristics/FisherTestHeuristic.R", chdir = TRUE)
source("source/clustering/heuristics/GainRatioHeuristic.R", chdir = TRUE)
source("source/clustering/heuristics/InformationGainHeuristic.R", chdir = TRUE)
source("source/clustering/heuristics/KendallHeuristic.R", chdir = TRUE)
source("source/clustering/heuristics/MultinformationHeuristic.R", chdir = TRUE)
source("source/clustering/heuristics/OddsRatioHeuristic.R", chdir = TRUE)
source("source/clustering/heuristics/OddsRatioSHeuristic.R", chdir = TRUE)
source("source/clustering/heuristics/PearsonHeuristic.R", chdir = TRUE)
source("source/clustering/heuristics/SpearmanHeuristic.R", chdir = TRUE)
source("source/clustering/heuristics/MCCHeuristic.R", chdir = TRUE)

source("source/clustering/plot/GenericPlot.R", chdir = TRUE)
source("source/clustering/plot/BinaryPlot.R", chdir = TRUE)
source("source/clustering/plot/KendallPlot.R", chdir = TRUE)
source("source/clustering/plot/SpearmanPlot.R", chdir = TRUE)
source("source/clustering/plot/SimplePlot.R", chdir = TRUE)

source("source/clustering/strategies/StrategyConfiguration.R", chdir = TRUE)
source("source/clustering/strategies/DependencyBasedStrategyConfiguration.R", chdir = TRUE)

source("source/clustering/strategies/GenericStrategy.R", chdir = TRUE)
source("source/clustering/strategies/SimpleStrategy.R", chdir = TRUE)
source("source/clustering/strategies/DependencyBasedStrategy.R", chdir = TRUE)
source("source/clustering/strategies/BinaryRealTypeStrategy.R", chdir = TRUE)

#LOAD MODEL CLASSES
cat("[SOURCES][INFO] Loading ML models and information handlers\n")
source("source/models/trainFunctions/TrainFunction.R", chdir= TRUE)
source("source/models/trainFunctions/TwoClass.R", chdir = TRUE)
source("source/models/summaryFunction/SummaryFunction.R",chdir = TRUE)
source("source/models/summaryFunction/NoProbability.R", chdir=TRUE)
source("source/models/summaryFunction/UseProbability.R", chdir=TRUE)
source("source/models/utility/DefaultModelFit.R",chdir=TRUE)
source("source/models/utility/GenericModelFit.R",chdir=TRUE)
source("source/models/Model.R", chdir=TRUE)
source("source/models/ExecutedModels.R",chdir=TRUE)
source("source/models/ClassifierPerformance.R", chdir=TRUE)
source("source/models/PerformanceComparator.R", chdir=TRUE)

#LOAD PREDICTION CLASSES
cat("[SOURCES][INFO] Loading Predicction classes\n")
source("source/prediction/Prediction.R", chdir=TRUE)
source("source/prediction/ClusterPredictions.R", chdir=TRUE)
source("source/prediction/VotingScheme.R", chdir=TRUE)
source("source/prediction/ClassWeightedVoting.R", chdir = TRUE)
source("source/prediction/ClassMajorityVoting.R", chdir=TRUE)
source("source/prediction/ProbMajorityVoting.R", chdir=TRUE)
source("source/prediction/PerformanceMeasures.R", chdir=TRUE)
source("source/prediction/ClassificationOutput.R", chdir=TRUE)
source("source/prediction/TrainOutput.R", chdir=TRUE)

#LOAD PREDICTION ALGORITHMS
cat("[SOURCES][INFO] Loading Optimization algorithms and utilities\n")
source("source/optimization/MinFunction.R", chdir = TRUE)
source("source/optimization/FPFN.R", chdir = TRUE)
source("source/optimization/WeightsOptimizer.R", chdir = TRUE)
source("source/optimization/NSGA2.R", chdir = TRUE)
source("source/optimization/SMSEMOA.R", chdir=TRUE)
source("source/optimization/OptimizationOutput.R", chdir=TRUE)
source("source/optimization/ParetoDistance.R", chdir=TRUE)
source("source/optimization/EuclideanDistance.R", chdir=TRUE)
source("source/optimization/MinimumFP.R", chdir=TRUE)
source("source/optimization/MinResult.R", chdir=TRUE)
source("source/optimization/MOOData.R", chdir = TRUE)
source("source/optimization/FPFNdata.R", chdir=TRUE)
source("source/optimization/SOO.R", chdir=TRUE)
source("source/optimization/SOOData.R", chdir=TRUE)
source("source/optimization/Optimizers.R", chdir= TRUE)

#LOAD MEASURES ALGORITHMS
cat("[SOURCES][INFO] Loading measure techniques\n")
source("source/measures/MeasureFunction.R", chdir = TRUE)
source("source/measures/Accuracy.R", chdir = TRUE)
source("source/measures/Kappa.R", chdir = TRUE)
source("source/measures/MCC.R", chdir = TRUE)
source("source/measures/NPV.R", chdir = TRUE)
source("source/measures/PPV.R", chdir = TRUE)
source("source/measures/Precision.R", chdir = TRUE)
source("source/measures/Recall.R", chdir = TRUE)
source("source/measures/Sensitivity.R", chdir = TRUE)
source("source/measures/Specificity.R", chdir = TRUE)
source("source/measures/ConfMatrix.R", chdir = TRUE)
source("source/measures/TP.R", chdir = TRUE)
source("source/measures/TN.R", chdir = TRUE)
source("source/measures/FN.R", chdir = TRUE)
source("source/measures/FP.R", chdir = TRUE)

cat("[SOURCES][INFO] Loading D2MCS core\n")
source("D2MCS.R", chdir = TRUE)
