#source("pkgChecker.R", chdir = TRUE)
source("source/data/Dataset.R", chdir=TRUE)
source("source/clustering/Cluster.R", chdir=TRUE)
source("source/clustering/ClusterDistribution.R", chdir=TRUE)
source("source/clustering/BinaryFisherData.R", chdir=TRUE)
source("source/clustering/MultiTypeClustering.R", chdir=TRUE)
source("source/models/utility/ModelFit.R", chdir = TRUE)
source("source/models/utility/DefaultModelFit.R", chdir = TRUE)
source("source/clustering/BinaryFisherClustering.R", chdir=TRUE)
source("source/models/trainFunctions/TrainFunction.R", chdir= TRUE)
source("source/models/trainFunctions/TwoClass.R", chdir = TRUE)
source("source/models/summaryFunction/SummaryFunction.R",chdir = TRUE)
source("source/models/summaryFunction/NoProbability.R", chdir=TRUE)
source("source/models/summaryFunction/UseProbability.R", chdir=TRUE)
source("source/models/utility/ModelFormula.R", chdir=TRUE)
source("source/models/utility/DefaultModelFit.R",chdir=TRUE)
source("source/models/utility/ModelFit.R",chdir=TRUE)
source("source/models/Model.R", chdir=TRUE)
source("source/models/LoadModels.R",chdir=TRUE)
source("source/models/ModelEntry.R",chdir=TRUE)
source("source/models/ModelsList.R",chdir=TRUE)
source("source/models/Predictions.R", chdir=TRUE)
source("source/models/ExecutedModels.R", chdir=TRUE)
source("source/models/ExecutedModelsList.R", chdir=TRUE)
source("source/models/ModelInfo.R", chdir=TRUE)
source("source/prediction/Prediction.R", chdir=TRUE)
source("source/prediction/PredictionList.R", chdir=TRUE)
source("source/prediction/PredictionHandler.R", chdir=TRUE)
source("source/prediction/VotingScheme.R", chdir=TRUE)
source("source/prediction/ClassMajorityVoting.R", chdir=TRUE)
source("source/prediction/ProbMajorityVoting.R", chdir=TRUE)
source("source/prediction/PerformanceMeasures.R", chdir=TRUE)
source("source/prediction/ClassWeightedVoting.R", chdir = TRUE)
source("D2MCS.R",chdir=TRUE)

#Required for dual plot
library(gridExtra)
library(grid)
library(ggplot2)
library(lattice)

#Required for recode()
library(car)

#Required for strcmpi()
library(pracma)